<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>uuid</key>
        <string>C611D263-828B-4B18-8844-E6F0BE2BF7F1</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>name</key>
                <string>constant.character.escape.snippet</string>
                <key>match</key>
                <string>\\(\\|\$|`)</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.tabstop.snippet</string>
                    </dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.snippet</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>meta.structure.tabstop.snippet</string>
                <key>match</key>
                <string>(\$)(\d+)</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>(\$\{)(\d+)(:)</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.snippet</string>
                    </dict>
                </dict>
                <key>beginCaptures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.tabstop.snippet</string>
                    </dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.snippet</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.snippet</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>meta.structure.tabstop.snippet</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>$self</string>
                    </dict>
                </array>
                <key>end</key>
                <string>\}</string>
            </dict>
            <dict>
                <key>name</key>
                <string>meta.structure.tabstop.snippet</string>
                <key>beginCaptures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.tabstop.snippet</string>
                    </dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.snippet</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.snippet</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>\}</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.snippet</string>
                    </dict>
                </dict>
                <key>contentName</key>
                <string>string.regexp</string>
                <key>begin</key>
                <string>(\$\{)(\d+)(/)</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#escaped_char</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#substitution</string>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>string.env.snippet</string>
                    </dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.snippet</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>meta.structure.variable.snippet</string>
                <key>match</key>
                <string>(\$)([a-zA-Z_][a-zA-Z0-9_]*)</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>(\$\{)([a-zA-Z_][a-zA-Z0-9_]*)(:)</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.snippet</string>
                    </dict>
                </dict>
                <key>beginCaptures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>string.env.snippet</string>
                    </dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.snippet</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.snippet</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>meta.structure.variable.snippet</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>$self</string>
                    </dict>
                </array>
                <key>end</key>
                <string>\}</string>
            </dict>
            <dict>
                <key>name</key>
                <string>meta.structure.substitution.snippet</string>
                <key>beginCaptures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>string.env.snippet</string>
                    </dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.snippet</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.snippet</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>\}</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.snippet</string>
                    </dict>
                </dict>
                <key>contentName</key>
                <string>string.regexp</string>
                <key>begin</key>
                <string>(\$\{)([a-zA-Z_][a-zA-Z0-9_]*)(/)</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#escaped_char</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#substitution</string>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>begin</key>
                <string>`</string>
                <key>name</key>
                <string>string.interpolated.shell.snippet</string>
                <key>end</key>
                <string>`</string>
            </dict>
        </array>
        <key>name</key>
        <string>Snippet</string>
        <key>scopeName</key>
        <string>text.snippet</string>
        <key>repository</key>
        <dict>
            <key>condition</key>
            <dict>
                <key>begin</key>
                <string>\(\?\d:</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>string.regexp.condition</string>
                    </dict>
                </dict>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>string.regexp.condition</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>meta.structure.condition.regexp</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#replacements</string>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>:</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>string.regexp.condition</string>
                            </dict>
                        </dict>
                        <key>name</key>
                        <string>meta.structure.condition.regexp</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#replacements</string>
                            </dict>
                        </array>
                        <key>end</key>
                        <string>(?=\))</string>
                    </dict>
                </array>
                <key>end</key>
                <string>\)</string>
            </dict>
            <key>replacements</key>
            <dict>
                <key>name</key>
                <string>string.regexp.replacement</string>
                <key>match</key>
                <string>\$\d|\\[uUILE]</string>
            </dict>
            <key>substitution</key>
            <dict>
                <key>contentName</key>
                <string>text.substitution</string>
                <key>begin</key>
                <string>/</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.snippet</string>
                    </dict>
                </dict>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.snippet</string>
                    </dict>
                </dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#escaped_char</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#replacements</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#condition</string>
                    </dict>
                </array>
                <key>end</key>
                <string>/[mg]?</string>
            </dict>
            <key>escaped_char</key>
            <dict>
                <key>name</key>
                <string>constant.character.escape.regex</string>
                <key>match</key>
                <string>\\[/\\]</string>
            </dict>
        </dict>
    </dict>
</plist>
