<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>uuid</key>
        <string>27EAD0F5-6C24-41C7-A6A1-4BE1C3523507</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>name</key>
                <string>comment.completed.todotxt</string>
                <key>match</key>
                <string>^x\s.*$</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.other.priority.high.todotxt</string>
                <key>match</key>
                <string>^\(A\)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.other.priority.medium.todotxt</string>
                <key>match</key>
                <string>^\(B\)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.other.priority.low.todotxt</string>
                <key>match</key>
                <string>^\(C\)</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.context.todotxt</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>keyword.context.todotxt</string>
                <key>match</key>
                <string>(?&lt;=^|\s)(@)\S*</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.project.todotxt</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>keyword.other.project.todotxt</string>
                <key>match</key>
                <string>(?&lt;=^|\s)(\+)\S+</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.duedate.todotxt</string>
                    </dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.other.duedate.todotxt</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>constant.other.duedate.todotxt</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>meta.structure.duedate.todotxt</string>
                <key>match</key>
                <string>\b((?i)due)(:)([[:alnum:]-]+)</string>
            </dict>
        </array>
        <key>name</key>
        <string>Todo.txt</string>
        <key>scopeName</key>
        <string>text.todotxt</string>
        <key>fileTypes</key>
        <array>
            <string>todo.txt</string>
        </array>
    </dict>
</plist>
